name: build and deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: login to container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.CONTAINER_REGISTRY_URL }}
          username: ${{ secrets.CONTAINER_REGISTRY_USER }}
          password: ${{ secrets.CONTAINER_REGISTRY_SECRET }}
      - uses: docker/setup-buildx-action@v3
        with:
          driver: docker
      - name: build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.CONTAINER_REGISTRY_URL }}/parrot:latest
      - name: confirm images
        run: docker images
